### ISSUE TITLE
no genereated gcode, no log

### ISSUE THREAD

**Issue by Avatarsia** [mfx-inria/curvislicer#12]
Hi, 

i followed your instructions so far but i have a little trouble with the result in win11. 

.\curvislice.bat models/wing.stl works but there are some red lines in the running process that were not showen at the end because on the clean command. so is there a log ? 

It Shows:
Gcode generated at: C:/Users/.../curvislicer/models/wing.gcode
But the folder just have a wings.msh , wing_.csv, wing_.msh and wing_sf.obj

**Comment by Avatarsia** [comment]
just deleted the cls from the bat file and see the following errors 

Printer has no profiles directory
Printer has no materials directory

**Comment by dorcu** [comment]
It doesn't generate the .gcode file for me either. Do you know what the problem is?

**Comment by JuDePom** [comment]
Hi, 
Thanks a lot for trying Curvislicer, and let's make it work!

As Avatarsia, try to remove the **cls** command in curvislice.bat
Then run curvislice.bat models/wing.stl

Then, copy paste the full logs, and we'll try to find what is not working.
(I just runned it on a "fresh" computer, and everything went fine on Windows 10 for me)

**Comment by dorcu** [comment]
This is my log:

https://pastebin.com/raw/9iybzrQt

**Comment by dorcu** [comment]
I already have that set in the environment variables and it doesn't work either. I keep getting the same error message.

**Comment by Avatarsia** [comment]
i just tried this version here:
https://github.com/mfx-inria/curvislicer/releases

the call should be changed to ./curvislice.bat models\wing.stl instead curvislice.bat models\wing.stl

**Comment by dorcu** [comment]
Downloading the content from this URL https://github.com/mfx-inria/curvislicer/releases has worked for me.

Thank you very much for your help.
