### ISSUE TITLE
big mistake

### ISSUE THREAD

**Issue by xuyonglai** [mfx-inria/curvislicer#5]
**big mistake**
![image](https://user-images.githubusercontent.com/71511255/102050671-35f32400-3e1e-11eb-9072-3ed39d083f36.png)
cos should be sin!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by xuyonglai** [comment]
normal_threshold = thresholdArg.isSet()
                       ? thresholdArg.getValue()
                       : cos(max_theta * M_PI / 180);

**Comment by JuDePom** [comment]
Thank you,

It's edited 👍

**Comment by xuyonglai** [comment]
> Thank you,
> 
> It's edited 👍

sorry，it is my bad, cos is right  . sorry
